import { Color, FontFamily, Padding, Border, FontSize } from "../GlobalStyles2";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
    sidebarPosition: {
      backgroundColor: Color.colorsWhite100,
      left: 0,
      top: 0,
      overflow: "hidden",
    },
    childIconLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    figiftIconLayout: {
      width: 24,
      height: 24,
    },
    logout1Typo: {
      FontFamily: FontFamily.semiBold11,
      fontWeight: "500",
      position: "absolute",
    },
    freeGiftAwaitsTypo: {
      width: 144,
      FontFamily: FontFamily.label1Regular,
      textAlign: "left",
    },
    iconLayout2: {
      height: 16,
      width: 16,
    },
    activateFlexBox: {
      paddingVertical: Padding.p_8xs,
      justifyContent: "center",
      alignItems: "center",
    },
    iconLayout1: {
      height: 12,
      width: 12,
      
    },
    iconSearch: {
      height: 12,
      width: 12,
      marginLeft: -35,
    },
    
    elementsLayout: {
      height: 14,
      width: 23,
      marginLeft: 8,
    },
    trackPosition: {
      borderStyle: "solid",
      borderWidth: 1,
      borderRadius: Border.br_3xs,
      right: "0%",
      left: "0%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
      width: "100%",
    },
    bobIconLayout: {
      bottom: "7.14%",
      top: "7.14%",
      width: "52.17%",
      height: "85.71%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    devSpaceBlock: {
      paddingBottom: Padding.p_5xs,
      paddingRight: Padding.p_5xs,
      paddingTop: Padding.p_5xs,
      flexDirection: "row",
    },
    developersTypo: {
      color: Color.textPrimary,
      textAlign: "left",
      fontWeight: "500",
    },
    accountswitcherPosition: {
      marginLeft: -82.5,
      left: "50%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
    },
    accountIconLayout: {
      width: 28,
      height: 28,
    },
    helpSpaceBlock: {
      marginLeft: 16,
      flexDirection: "row",
    },
    iconPosition1: {
      right: 0,
      position: "absolute",
    },
    textLayout: {
      height: 13,
      position: "absolute",
    },
    iconLayout: {
      height: 11,
      width: 11,
    },
    iconParentFlexBox: {
      justifyContent: "center",
      alignItems: "center",
    },
    verifyLayout: {
      height: 267,
      width: 1153,
      position: "absolute",
    },
    groupItemLayout: {
      height: 6,
      width: 98,
      borderRadius: Border.br_21xl,
      position: "absolute",
    },
    groupLayout: {
      width: 34,
      height: 34,
      position: "absolute",
    },
    textTypo2: {
      lineHeight: 23,
      left: 12,
      fontSize: FontSize.bold16_size,
      FontFamily: FontFamily.label1Regular,
      textAlign: "left",
      position: "absolute",
    },
    text7Layout: {
      lineHeight: 24,
      textAlign: "left",
    },
    groupWrapperLayout: {
      width: 538,
      height: 34,
    },
    groupInnerLayout: {
      backgroundColor: Color.colorCornflowerblue,
      height: 6,
      width: 98,
      borderRadius: Border.br_21xl,
      top: 14,
      position: "absolute",
    },
    chartPosition1: {
      height: 328,
      top: 350,
      position: "absolute",
    },
    bgBorder: {
      borderColor: Color.colorGainsboro_200,
      borderStyle: "solid",
      position: "absolute",
    },
    linesPosition: {
      left: "3.01%",
      right: "3.14%",
      width: "93.85%",
      position: "absolute",
    },
    linesChildPosition: {
      borderTopWidth: 1,
      borderColor: Color.colorWhitesmoke_200,
      left: "-0.07%",
      right: "-0.07%",
      height: "0.63%",
      width: "100.13%",
      borderStyle: "solid",
      position: "absolute",
    },
    febTypo: {
      color: Color.gray600,
      lineHeight: 21,
      top: "90.83%",
      fontSize: FontSize.bold13_size,
      FontFamily: FontFamily.semiBold11,
      fontWeight: "500",
      position: "absolute",
    },
    textTypo1: {
      FontFamily: FontFamily.bold11,
      color: Color.gray900,
      fontWeight: "700",
    },
    bg1ShadowBox: {
      elevation: 44,
      shadowRadius: 44,
      shadowColor: "rgba(0, 0, 0, 0.08)",
      borderColor: Color.colorGainsboro_200,
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      borderWidth: 1,
      borderStyle: "solid",
      backgroundColor: Color.colorsWhite100,
    },
    buttonprimarywithIconPosition2: {
      padding: Padding.p_base,
      borderRadius: Border.br_8xs,
      justifyContent: "center",
      alignItems: "center",
      bottom: "0%",
      top: "0%",
      height: "100%",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
    },
    buttonTypo1: {
      marginLeft: 0,
      textAlign: "right",
      fontSize: FontSize.bold11_size,
      FontFamily: FontFamily.bold11,
      lineHeight: 18,
      fontWeight: "700",
    },
    buttonprimarywithIconPosition1: {
      left: "77.25%",
      width: "22.75%",
      right: "0%",
    },
    textTypo: {
      color: Color.valueColor,
      FontFamily: FontFamily.robotoMedium,
      textAlign: "left",
      fontWeight: "500",
    },
    bg2Position: {
      left: "-0.14%",
      borderColor: Color.colorGainsboro_200,
      borderStyle: "solid",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
    },
    textPosition: {
      left: "7.13%",
      position: "absolute",
    },
    buttonprimarywithIconPosition: {
      padding: 11,
      borderRadius: 3,
      justifyContent: "center",
      alignItems: "center",
      bottom: "0%",
      top: "0%",
      height: "100%",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
    },
    buttonTypo: {
      
      lineHeight: 15,
      fontSize: FontSize.size_3xs_2,
      textAlign: "center",
      FontFamily: FontFamily.bold11,
      fontWeight: "700",
    },
    buttonprimarywithIconLayout: {
      width: "22.75%",
      padding: 11,
      justifyContent: "center",
      borderRadius: 3,
      alignItems: "center",
      bottom: "0%",
      top: "0%",
      height: "100%",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
  },
    iconPosition: {
      bottom: "8.69%",
      top: "38.11%",
      height: "53.2%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    primaryTypo: {
      lineHeight: 27,
      left: "6.91%",
      color: Color.textPrimary,
      letterSpacing: 0,
      textAlign: "left",
      FontFamily: FontFamily.semiBold11,
      fontWeight: "500",
      position: "absolute",
    },
    titleTypo: {
      lineHeight: 19,
      fontSize: FontSize.size_sm_3,
      color: Color.textSecondary,
      letterSpacing: 0,
      textAlign: "left",
      FontFamily: FontFamily.semiBold11,
      fontWeight: "500",
    },
    deprecatedPosition: {
      bottom: "84.64%",
      top: "7.66%",
    },
    badgebaseSpaceBlock: {
      paddingVertical: 1,
      paddingHorizontal: 6,
      height: 17,
      borderRadius: 4,
      alignItems: "center",
      flexDirection: "row",
      overflow: "hidden",
    },
    badgeTypo: {
      fontSize: FontSize.size_xs_4,
      marginLeft: 3.8,
      lineHeight: 19,
      textAlign: "left",
      FontFamily: FontFamily.semiBold11,
      fontWeight: "500",
    },
    chartPosition: {
      top: 738,
      height: 222,
      width: 362,
      position: "absolute",
    },
    titlePosition: {
      left: "6.91%",
      position: "absolute",
    },
    deprecatedLayout: {
      width: "12.57%",
      height: "7.7%",
      flexDirection: "row",
      position: "absolute",
    },
    logoChild: {
      width: "33.59%",
      right: "66.41%",
      left: "0%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      maxHeight: "100%",
    },
    metrix: {
      left: 63,
      fontSize: FontSize.subHeading3Bold_size,
      FontFamily: FontFamily.subHeading3Bold,
      color: Color.black60,
      textAlign: "center",
      fontWeight: "700",
      top: 14,
      position: "absolute",
    },
    logo: {
      height: "5.08%",
      width: "52.31%",
      top: "1.37%",
      right: "36.03%",
      bottom: "93.56%",
      left: "11.66%",
      display: "none",
      position: "absolute",
    },
    logoutChild: {
      width: 79,
      alignItems: "center",
      height: 24,
    },
    logout: {
      backgroundColor: Color.colorIndianred,
      paddingTop: Padding.p_2xs,
      paddingRight: Padding.p_2xs,
      paddingBottom: Padding.p_2xs,
      borderRadius: Border.br_base,
    },
    bottom: {
      top: 943,
      left: 16,
      flexDirection: "row",
      position: "absolute",
    },
    iconlybulklogout: {
      top: 848,
      left: 26,
      position: "absolute",
    },
    logout1: {
      height: "2.25%",
      width: "25.51%",
      top: "81.07%",
      left: "22.67%",
      color: Color.destructive600,
      textAlign: "left",
      fontSize: FontSize.bodyL18SpRegular_size,
      FontFamily: FontFamily.semiBold11,
    },
    figiftIcon: {
      overflow: "hidden",
    },
    freeGiftAwaits: {
      color: Color.black100,
      height: 19,
      marginLeft: 12,
      fontSize: FontSize.deprecatedBodyAlt_size,
    },
    figiftParent: {
      alignItems: "flex-end",
      flexDirection: "row",
    },
    upgradeYourAccount: {
      color: Color.black40,
      height: 18,
      display: "flex",
      fontSize: FontSize.semiBold11_size,
      alignItems: "center",
    },
    fichevronDownIcon: {
      overflow: "hidden",
    },
    upgradeYourAccountParent: {
      marginTop: 16,
      alignItems: "center",
      flexDirection: "row",
    },
    container: {
      top: 11,
      left: 20,
      position: "absolute",
    },
    banner: {
      top: 836,
      left: 32,
      backgroundColor: Color.colorBurlywood,
      width: 233,
      height: 82,
      borderRadius: Border.br_base,
      display: "none",
      position: "absolute",
      overflow: "hidden",
    },
    businessIcon: {
      top: 30,
      left: 26,
      position: "absolute",
    },
    activateAccount: {
      color: Color.attention600,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      lineHeight: 16,
      fontSize: FontSize.semiBold11_size,
      textAlign: "left",
      fontWeight: "500",
    },
    arrowrightIcon: {
      marginLeft: 8,
    },
    activateButton: {
      top: 61,
      paddingHorizontal: Padding.p_3xs,
      backgroundColor: Color.attention100,
      borderRadius: Border.br_18xl,
      paddingVertical: Padding.p_8xs,
      height: 24,
      left: 46,
      position: "absolute",
      flexDirection: "row",
    },
    testData: {
      color: Color.textAttention,
      lineHeight: 20,
      letterSpacing: 0,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      fontSize: FontSize.deprecatedBodyAlt_size,
      textAlign: "left",
      fontWeight: "500",
    },
    track: {
      borderColor: Color.neutral100,
      borderWidth: 1,
      backgroundColor: Color.backgroundsContainer,
      borderStyle: "solid",
    },
    bobIcon: {
      right: "43.48%",
      left: "4.35%",
    },
    elementsLivemodeswitchoff: {
      display: "none",
    },
    track1: {
      backgroundColor: Color.attention400,
      borderColor: Color.attention400,
      borderWidth: 1,
    },
    bobIcon1: {
      right: "4.35%",
      left: "43.48%",
    },
    testdata: {
      top: 800,
      left: 24,
      paddingLeft: Padding.p_3xs,
      paddingTop: Padding.p_3xs,
      paddingBottom: Padding.p_3xs,
      alignItems: "center",
      flexDirection: "row",
      position: "absolute",
    },
    codeIcon: {
      width: 20,
      height: 20,
      overflow: "hidden",
    },
    developers: {
      textDecoration: "underline",
      FontFamily: FontFamily.textXsMedium,
      lineHeight: 20,
      letterSpacing: 0,
      fontSize: FontSize.deprecatedBodyAlt_size,
    },
    dev: {
      top: 771,
      left: 30,
      width: 103,
      position: "absolute",
    },
    sidebar: {
      width: 247,
      position: "absolute",
      height: 1046,
    },
    accountIcon: {
      height: 28,
      display: "none",
    },
    accountName: {
      FontFamily: FontFamily.plusJakartaSansSemiBold,
      color: Color.neutral500,
      fontWeight: "600",
      marginLeft: 8,
      lineHeight: 16,
      fontSize: FontSize.semiBold11_size,
      textAlign: "left",
    },
    accountswitcher: {
      alignItems: "center",
      flexDirection: "row",
    },
    accountswitcherWrapper: {
      width: 165,
    },
    dashboardInner: {
      height: "1.53%",
      marginLeft: -671,
      top: "2.87%",
      bottom: "95.6%",
      width: 165,
      left: "50%",
      position: "absolute",
    },
    search1: {
      width: 420,
      color: Color.textSecondary,
      marginLeft: 8,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      lineHeight: 16,
      fontSize: FontSize.semiBold11_size,
      textAlign: "left",
    },
    search: {
      marginTop: -12.75,
      marginLeft: -228.5,
      top: "50%",
      borderColor: Color.colorGainsboro_100,
      paddingHorizontal: Padding.p_5xs,
      paddingVertical: Padding.p_9xs,
      borderRadius: Border.br_xs,
      left: "50%",
      borderWidth: 1,
      borderStyle: "solid",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      display: "none",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
    },
    create: {
      color: Color.textBrand,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      lineHeight: 16,
      fontSize: FontSize.semiBold11_size,
      textAlign: "left",
      fontWeight: "500",
    },
    chevrondownIcon: {
      marginLeft: 4,
    },
    createButton: {
      borderColor: Color.textBrand,
      borderRadius: Border.br_21xl,
      paddingVertical: Padding.p_9xs,
      borderWidth: 1,
      borderStyle: "solid",
      paddingHorizontal: Padding.p_3xs,
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
    },
    help1: {
      color: Color.neutral600,
      marginLeft: 4,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      lineHeight: 16,
      fontSize: FontSize.semiBold11_size,
      textAlign: "left",
    },
    help: {
      justifyContent: "center",
      alignItems: "center",
    },
    notificationsIcon: {
      height: 16,
      width: 16,
      top: 0,
    },
    backgroundIcon: {
      top: 1,
      right: 0,
      position: "absolute",
    },
    text: {
      fontSize: FontSize.size_smi_2,
        lineHeight: 17,
        color: Color.textIconsSecondary,
        FontFamily: FontFamily.deprecatedCaptionAlt,
        letterSpacing: 0,
        fontWeight: "500",
        textAlign: "center",
    },
    badgeCount: {
      top: -4,
      right: -7,
      width: 11,
      height: 13,
    },
    settingsIcon: {
      marginLeft: 24,
    },
    rightGroup: {
      right: 40,
      top: 4,
      alignItems: "center",
      flexDirection: "row",
      position: "absolute",
    },
    accountIcon1: {
      height: 28,
    },
    accountName1: {
      marginLeft: 8,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      lineHeight: 16,
      fontSize: FontSize.semiBold11_size,
    },
    accountswitcher1: {
      alignItems: "center",
      flexDirection: "row",
    },
    accountswitchercactuspractice: {
      flexDirection: "row",
      display: "none",
    },
    activateButton1: {
      paddingVertical: Padding.p_8xs,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: Padding.p_3xs,
      backgroundColor: Color.attention100,
      borderRadius: Border.br_18xl,
      height: 24,
      display: "none",
    },
    leftGroup: {
      left: 40,
      width: 302,
      top: 6,
      height: 28,
      flexDirection: "row",
      position: "absolute",
    },
    toolbar: {
      height: "3.01%",
      width: "82.85%",
      bottom: "96.99%",
      left: "17.15%",
      shadowColor: "rgba(108, 140, 171, 0.15)",
      shadowRadius: 0,
      elevation: 0,
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      backgroundColor: Color.backgroundsContainer,
      right: "0%",
      top: "0%",
      position: "absolute",
    },
    rightBand2: {
      top: 63,
      left: 781,
      width: 527,
      height: 158,
      position: "absolute",
    },
    rightBand1: {
      top: -16,
      left: 804,
      width: 505,
      height: 161,
      opacity: 0.5,
      position: "absolute",
    },
    verifyYourAccountChild: {
      top: 110,
      left: 595,
      backgroundColor: "#f3f4f6",
    },
    ellipseParent: {
      height: 34,
      left: 0,
      top: 0,
    },
    text1: {
      color: Color.neutral6001,
      top: 6,
    },
    verifyYourAccountInner: {
      top: 96,
      left: 711,
      height: 34,
    },
    verifyYourAccount: {
      borderRadius: Border.br_xs,
      backgroundColor: Color.colorsWhite100,
      left: 0,
      top: 0,
      overflow: "hidden",
    },
    verifyYourAccount1: {
      fontSize: 32,
      FontFamily: FontFamily.interSemiBold,
      color: Color.neutral900,
      fontWeight: "600",
    },
    groupItem: {
      left: 52,
      backgroundColor: "rgba(99, 91, 255, 0.5)",
      top: 14,
      width: 98,
    },
    groupInner: {
      left: 220,
    },
    rectangleView: {
      left: 388,
    },
    text2: {
      left: 13,
      lineHeight: 18,
      fontSize: FontSize.bold16_size,
      color: Color.colorsWhite100,
      top: 8,
      FontFamily: FontFamily.label1Regular,
      textAlign: "left",
      position: "absolute",
    },
    text3: {
      top: 5,
      color: Color.colorsWhite100,
    },
    groupFrame: {
      left: 168,
      height: 34,
      top: 0,
    },
    text4: {
      top: 6,
      color: Color.colorsWhite100,
    },
    groupView: {
      left: 336,
      height: 34,
      top: 0,
    },
    groupWrapper1: {
      left: 504,
      height: 34,
      top: 0,
    },
    rectangleParent: {
      left: 0,
      top: 0,
      position: "absolute",
    },
    groupWrapper: {
      marginTop: 25,
    },
    tellUsMore: {
      color: Color.black,
      FontFamily: FontFamily.label1Regular,
      lineHeight: 24,
      fontSize: FontSize.bodyL18SpRegular_size,
    },
    continue: {
      fontSize: FontSize.bold16_size,
      lineHeight: 24,
      color: Color.colorsWhite100,
      FontFamily: FontFamily.textXsMedium,
      fontWeight: "500",
    },
    fillArrowLeft: {
      marginLeft: 5,
    },
    cta: {
      borderRadius: Border.br_7xs,
      backgroundColor: Color.textIconsBrand,
      paddingHorizontal: 190,
      width: 265,
      flexDirection: "row",
      left: 0,
      top: 0,
      position: "absolute",
    },
    ctaWrapper: {
      width: 265,
      height: 34,
      marginTop: 16,
    },
    tellUsMoreAboutYourBusineParent: {
      marginTop: 22,
    },
    group: {
      top: 47,
      left: 38,
      position: "absolute",
    },
    verifyYourAccountParent: {
      top: 70,
      left: 259,
    },
    text6: {
      fontSize: FontSize.size_smi_2,
      lineHeight: 17,
      color: Color.textIconsSecondary,
      letterSpacing: 0,
      FontFamily: FontFamily.deprecatedCaptionAlt,
      fontWeight: "500",
      textAlign: "center",
    },
    rightSectionIcon: {
      width: 10,
      height: 10,
      marginLeft: 7,
    },
    dateControlChild: {
      marginLeft: 7,
      height: 24,
      maxWidth: "100%",
      overflow: "hidden",
    },
    dateControl: {
      width: "101.75%",
      top: -1,
      right: "-0.82%",
      left: "-0.93%",
      borderColor: Color.colorDarkslategray_100,
      borderWidth: 0.9,
      height: 26,
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 3,
      borderStyle: "solid",
      alignItems: "center",
      flexDirection: "row",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
    },
    dateControlWrapper: {
      width: "6.74%",
      top: 706,
      right: "74.86%",
      left: "18.4%",
      height: 24,
      position: "absolute",
    },
    bg: {
      height: "100.3%",
      top: "-0.15%",
      right: "-0.06%",
      bottom: "-0.15%",
      left: "-0.06%",
      width: "100.13%",
      borderColor: Color.colorGainsboro_200,
      borderWidth: 1,
      borderRadius: Border.br_3xs,
      backgroundColor: Color.colorsWhite100,
    },
    linesChild: {
      top: "99.69%",
      bottom: "-0.31%",
    },
    linesItem: {
      top: "74.69%",
      bottom: "24.69%",
    },
    linesInner: {
      top: "49.69%",
      bottom: "49.69%",
    },
    lineView: {
      top: "24.69%",
      bottom: "74.69%",
    },
    linesChild1: {
      top: "-0.31%",
      bottom: "99.69%",
    },
    lines: {
      height: "48.78%",
      top: "32.93%",
      bottom: "18.29%",
    },
    bgIcon: {
      height: "82.53%",
      bottom: "17.47%",
      right: "0%",
      maxHeight: "100%",
      maxWidth: "100%",
      left: "0%",
      top: "0%",
      position: "absolute",
      overflow: "hidden",
      width: "100%",
    },
    feb: {
      left: "0.13%",
      textAlign: "left",
    },
    mar: {
      left: "8.96%",
      textAlign: "center",
    },
    apr: {
      left: "17.78%",
      textAlign: "center",
    },
    may: {
      left: "26.34%",
      textAlign: "center",
    },
    jun: {
      left: "35.43%",
      textAlign: "center",
    },
    jul: {
      left: "43.58%",
      textAlign: "center",
    },
    aug: {
      left: "51.34%",
      textAlign: "center",
    },
    sep: {
      left: "60.29%",
      textAlign: "center",
    },
    oct: {
      left: "69.39%",
      textAlign: "center",
    },
    nov: {
      left: "78.34%",
      textAlign: "center",
    },
    dec: {
      left: "87.3%",
      textAlign: "center",
    },
    jan: {
      left: "96.39%",
      textAlign: "center",
    },
    graph: {
      height: "69.82%",
      top: "23.78%",
      bottom: "6.4%",
    },
    chartChild: {
      height: "22.26%",
      width: "0.13%",
      top: "59.3%",
      right: "62.55%",
      bottom: "18.45%",
      left: "37.33%",
      borderRightWidth: 1,
    },
    chartItem: {
      height: "3.05%",
      width: "1.25%",
      top: "56.4%",
      right: "61.98%",
      bottom: "40.55%",
      left: "36.76%",
    },
    text7: {
      top: "6.1%",
      color: Color.gray900,
      left: "3.14%",
      position: "absolute",
      lineHeight: 24,
      textAlign: "left",
      fontSize: FontSize.bold16_size,
    },
    unionChild: {
      height: "17.46%",
      width: "18.75%",
      top: "279.37%",
      right: "-219.79%",
      bottom: "-196.83%",
      left: "301.04%",
    },
    bg1: {
      height: "90.48%",
      top: "179.37%",
      right: "-260.42%",
      bottom: "-169.84%",
      left: "260.42%",
      borderRadius: Border.br_5xs,
      position: "absolute",
      width: "100%",
    },
    union: {
      width: 96,
      height: 63,
    },
    text8: {
      top: "41.27%",
      left: "32.29%",
      lineHeight: 22,
      color: Color.gray900,
      fontSize: FontSize.bold13_size,
      FontFamily: FontFamily.bold11,
      textAlign: "center",
      position: "absolute",
    },
    june2022: {
      top: "12.7%",
      left: "19.79%",
      color: Color.gray500,
      lineHeight: 20,
      fontSize: FontSize.semiBold11_size,
      textAlign: "center",
    },
    popup: {
      height: "19.21%",
      width: "12.05%",
      top: "34.45%",
      right: "56.59%",
      bottom: "46.34%",
      left: "31.37%",
      position: "absolute",
    },
    icon: {
      width: 18,
      height: 18,
      display: "none",
    },
    buttonName: {
      color: Color.gray500,
    },
    iconParent: {
      width: 126,
      flexDirection: "row",
    },
    buttonprimarywithIconLeft: {
      width: "23.65%",
      right: "76.35%",
      
      borderStyle: "solid",
      left: "0%",
      
    },
    buttonName1: {
      color: Color.gray500,
    },
    buttonprimarywithIconLeft1: {
      right: "50.9%",
      left: "26.35%",
      width: "22.75%",
    },
    buttonprimarywithIconLeft2: {
      right: "25.45%",
      left: "51.8%",
      width: "22.75%",
    },
    buttonprimarywithIconLeft3: {
      padding: Padding.p_base,
      borderRadius: Border.br_8xs,
      justifyContent: "center",
      alignItems: "center",
      bottom: "0%",
      top: 300,
      height: "100%",
      backgroundColor: Color.colorsWhite100,
      position: "absolute",
    },
    
    buttonprimarywithIconLeftParent: {
      
      top: "5.18%",
      right: "28.98%",
      bottom: "85.67%",
      left: "29.11%",
      position: "absolute",
    },
    text9: {
      width: "10.41%",
      top: "15.24%",
      fontSize: FontSize.size_15xl_9,
      letterSpacing: -1.3,
      left: "3.14%",
      position: "absolute",
    },
    glyphIcon: {
      height: "1.52%",
      width: "1.13%",
      top: "9.76%",
      right: "75.78%",
      bottom: "88.72%",
      left: "23.09%",
    },
    chart: {
      width: 797,
      left: 259,
      borderRadius: Border.br_xs,
    },
    bg2: {
      height: "100.24%",
      width: "100.31%",
      top: "-0.12%",
      right: "-0.17%",
      bottom: "-0.12%",
      borderRadius: 8,
      borderWidth: 0.8,
    },
    glyphIcon1: {
      height: "1.86%",
      width: "3.63%",
      top: "7.93%",
      right: "49.35%",
      bottom: "90.21%",
      left: "47.01%",
    },
    text10: {
      top: "5.12%",
      fontSize: FontSize.size_sm_4,
      color: Color.gray900,
      FontFamily: FontFamily.bold11,
      fontWeight: "700",
      lineHeight: 20,
      textAlign: "left",
    },
    icon4: {
      display: "none",
    },
    buttonName4: {
      color: Color.gray500,
    },
    iconParent1: {
      width: 84,
      flexDirection: "row",
    },
    buttonprimarywithIconLeft4: {
      width: "23.66%",
      right: "76.34%",
      borderWidth: 0,
      left: "0%",
    },
    buttonName5: {
      color: Color.gray500,
    },
    buttonprimarywithIconLeft5: {
      right: "50.93%",
      left: "26.32%",
      width: "22.75%",
    },
    buttonprimarywithIconLeft6: {
      right: "25.46%",
      left: "51.78%",
      width: "22.75%",
    },
    buttonprimarywithIconLeft7: {
      left: "77.25%",
      width: "22.75%",
      right: "0%",
    },
    buttonprimarywithIconLeftGroup: {
      height: "6.07%",
      width: "75.24%",
      top: "26.37%",
      right: "17.63%",
      bottom: "67.56%",
    },
    bgIcon1: {
      width: "89.2%",
      right: "3.97%",
      left: "6.83%",
    },
    text11: {
      width: "23.64%",
      top: "11.49%",
      fontSize: FontSize.size_10xl_3,
      letterSpacing: -1.1,
      color: Color.valueColor,
      FontFamily: FontFamily.robotoMedium,
      textAlign: "left",
      fontWeight: "500",
    },
    chart5: {
      left: 1086,
      width: 294,
    },
    bg3: {
      height: "100.45%",
      width: "100.28%",
      top: "-0.23%",
      right: "-0.14%",
      bottom: "-0.23%",
      borderWidth: 1,
      borderRadius: Border.br_3xs,
      left: "-0.14%",
    },
    bgIcon2: {
      width: "89.17%",
      right: "3.98%",
      left: "6.85%",
    },
    text12: {
      fontSize: FontSize.size_lg_9,
    },
    documentsTransfered: {
      fontSize: FontSize.semiBold11_size,
    },
    primary: {
      top: "16.58%",
    },
    title: {
      top: "6.76%",
      left: "6.91%",
      position: "absolute",
    },
    leftwrapperIcon: {
      display: "none",
    },
    badgeLabel: {
      color: Color.success600,
      marginLeft: 3.8,
    },
    rightwrapperIcon: {
      marginLeft: 3.8,
      display: "none",
    },
    badgebase: {
      backgroundColor: Color.success100,
    },
    deprecatedBadge: {
      width: "13.09%",
      right: "48.81%",
      left: "38.09%",
      height: "7.7%",
      bottom: "84.64%",
      top: "7.66%",
      flexDirection: "row",
      position: "absolute",
    },
    chart2: {
      top: 743,
      left: 264,
      height: 222,
      width: 362,
      position: "absolute",
    },
    primary1: {
      height: "9.01%",
      width: "64.36%",
      top: "16.67%",
    },
    titleWrapper: {
      height: "15.77%",
      width: "26.8%",
      top: "3.6%",
      right: "66.3%",
      bottom: "80.63%",
      paddingBottom: Padding.p_5xs,
      paddingRight: Padding.p_5xs,
      paddingTop: Padding.p_5xs,
      flexDirection: "row",
    },
    badgeLabel1: {
      marginLeft: 3.8,
      color: Color.attention600,
    },
    badgebase1: {
      backgroundColor: Color.colorMistyrose,
    },
    deprecatedBadge1: {
      right: "53.73%",
      left: "33.7%",
      bottom: "84.64%",
      top: "7.66%",
    },
    chart3: {
      left: 643,
    },
    primary2: {
      top: "18.38%",
      fontSize: FontSize.size_lg_9,
    },
    title2: {
      top: "8.56%",
      left: "6.91%",
      position: "absolute",
    },
    deprecatedBadge2: {
      top: "9.46%",
      right: "62.54%",
      bottom: "82.84%",
      left: "24.89%",
    },
    chart4: {
      left: 1022,
    },
    dashboard: {
      backgroundColor: Color.colorGray_100,
      flex: 1,
      overflow: "hidden",
      height: 1046,
      width: "100%",
    },
    searchWrapper: {
      left: 492,
      width: 456,
      top: 4,
      height: 24,
      position: "absolute",
  },
  search2: {
    marginTop: -13,
    marginLeft: -229,
    paddingHorizontal: Padding.p_5xs,
    borderColor: Color.colorGainsboro_100,
    borderRadius: Border.br_xs,
    paddingVertical: Padding.p_9xs,
    top: "50%",
    left: "50%",
    backgroundColor: Color.colorsWhite100,
    position: "absolute",
    width: 494,
},
searchFlexBox: {
  paddingVertical: Padding.p_9xs,
  justifyContent: "center",
  borderWidth: 1,
  borderStyle: "solid",
  alignItems: "center",
  flexDirection: "row",
},
//selected button
selectedButton: {
  borderColor: '#000', // Replace with the desired border color for the selected state
  borderWidth: 1, // Adjust the border width if needed

},
selectedText: {
  color: '#000', // Replace with the desired text color for the selected state
},
//selected button install
selectedButtonInstall: {
  borderColor: '#000', // Replace with the desired border color for the selected state
  borderWidth: 1, // Adjust the border width if needed

},
selectedTextInstall: {
  color: '#000', // Replace with the desired text color for the selected state
},
groupIconFlexBox: {
  justifyContent: "center",
  alignItems: "center",
},
buttonprimarywithIconLayout1: {
  width: "22.76%",
  padding: Padding.p_base,
  borderRadius: Border.br_8xs,
  justifyContent: "center",
  alignItems: "center",
  bottom: "0%",
  top: "0%",
  height: "100%",
  backgroundColor: Color.colorsWhite100,
  position: "absolute",
},
buttonprimarywithIconLayout2: {
  width: "22.76%",
  padding: Padding.p_base,
  borderRadius: Border.br_8xs,
  justifyContent: "center",
  alignItems: "center",
  bottom: "0%",
  top: "0%",
  height: "100%",
  left: "77.24%",
  backgroundColor: Color.colorsWhite100,
  position: "absolute",
},
  });