import { FontFamily, Color, Border, Padding, FontSize } from "../GlobalStyles2";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
    //loader
    loaderContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
    iconChildLayout: {
        maxHeight: "100%",
        maxWidth: "100%",
        position: "absolute",
        overflow: "hidden",
    },
    figiftIconLayout: {
        width: 24,
        height: 24,
    },
    logout1Typo: {
        FontFamily: FontFamily.semiBold11,
        fontWeight: "500",
        position: "absolute",
    },
    freeGiftAwaitsTypo: {
        width: 144,
        FontFamily: FontFamily.label1Regular,
        textAlign: "left",
    },
    iconLayout2: {
        height: 16,
        width: 16,
    },

    testDataTypo: {
        color: Color.textPrimary,
        FontFamily: FontFamily.deprecatedCaptionAlt,
        fontWeight: "500",
    },
    bg3Layout: {
        borderWidth: 1,
        borderRadius: Border.br_3xs,
    },
    accountswitcherPosition: {
        marginLeft: 0,
        left: -22,
        top: 24,
        height: "100%",
        position: "absolute",
        FontFamily: FontFamily.plusJakartaSansSemiBold,
    },
    accountIconLayout: {
        height: 28,
        width: 28,
        top: 26,
        left: 41
    },
    text1Typo: {
        fontWeight: "600",
        lineHeight: 16,
    },
    iconLayout1: {
        height: 12,
        width: 12,
    },
    ellipseIconLayout: {
        bottom: "9.73%",
        top: "89.97%",
        width: "0.3%",
        height: "0.31%",
        maxHeight: "100%",
        maxWidth: "100%",
        position: "absolute",
        overflow: "hidden",
    },
    searchFlexBox: {
        paddingVertical: Padding.p_9xs,
        justifyContent: "center",
        borderWidth: 1,
        borderStyle: "solid",
        alignItems: "center",
        flexDirection: "row",
    },
    groupIconFlexBox: {
        justifyContent: "center",
        alignItems: "center",
    },
    accountTypo: {
        lineHeight: 16,
        fontSize: FontSize.semiBold11_size,
        textAlign: "left",
    },
    helpSpaceBlock: {
        marginLeft: 16,
        flexDirection: "row",
    },
    iconPosition1: {
        right: 0,
        position: "absolute",
    },
    text1Layout: {
        height: 13,
        position: "absolute",
    },
    iconLayout: {
        height: 11,
        width: 11,
    },
    trackBorder: {
        borderColor: Color.neutral100,
        borderStyle: "solid",
        position: "absolute",
    },
    chartPosition1: {
        height: 328,
        top: 67,
        position: "absolute",
    },
    bgBorder: {
        borderColor: Color.colorGainsboro_200,
        borderStyle: "solid",
        position: "absolute",
    },
    linesPosition: {
        left: "3.01%",
        right: "3.13%",
        width: "93.86%",
        position: "absolute",
    },
    linesChildPosition: {
        borderTopWidth: 1,
        borderColor: Color.colorWhitesmoke_200,
        width: "100.13%",
        height: "0.63%",
        left: "-0.06%",
        right: "-0.06%",
        borderStyle: "solid",
        position: "absolute",
    },
    febTypo: {
        color: Color.gray600,
        lineHeight: 21,
        top: "90.83%",
        fontSize: FontSize.bold13_size,
        FontFamily: FontFamily.semiBold11,
        fontWeight: "500",
        position: "absolute",
    },
    textTypo1: {
        FontFamily: FontFamily.bold11,
        color: Color.gray900,
        fontWeight: "700",
    },
    bg1ShadowBox: {
        elevation: 44,
        shadowRadius: 44,
        shadowColor: "rgba(0, 0, 0, 0.08)",
        borderColor: Color.colorGainsboro_200,
        shadowOpacity: 1,
        shadowOffset: {
            width: 0,
            height: 1,
        },
        borderWidth: 1,
        borderStyle: "solid",
        backgroundColor: Color.colorsWhite100,
    },
    buttonTypo1: {

        textAlign: "right",
        lineHeight: 18,
        fontSize: FontSize.bold11_size,
        FontFamily: FontFamily.bold11,
        fontWeight: "700",
    },
    buttonprimarywithIconLayout1: {
        width: "22.76%",
        padding: Padding.p_base,
        borderRadius: Border.br_8xs,
        justifyContent: "center",
        alignItems: "center",
        bottom: "0%",
        top: "0%",
        height: "100%",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",

    },
    textTypo: {
        color: Color.valueColor,
        FontFamily: FontFamily.robotoMedium,
        textAlign: "left",
        fontWeight: "500",
    },
    bg2Position: {
        left: "-0.14%",
        borderColor: Color.colorGainsboro_200,
        borderStyle: "solid",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",
    },
    textPosition: {
        left: "7.13%",
        position: "absolute",
    },
    buttonTypo: {

        lineHeight: 15,
        fontSize: FontSize.size_3xs_2,
        textAlign: "right",
        FontFamily: FontFamily.bold11,
        fontWeight: "700",
    },
    buttonprimarywithIconLayout: {
        width: "22.75%",
        padding: 11,
        justifyContent: "center",
        borderRadius: 3,
        alignItems: "center",
        bottom: "0%",
        top: "0%",
        height: "100%",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",
    },
    iconPosition: {
        bottom: "8.69%",
        top: "38.11%",
        height: "53.2%",
        maxHeight: "100%",
        maxWidth: "100%",
        position: "absolute",
        overflow: "hidden",
    },
    chartLayout: {
        height: 222,
        width: 362,
        position: "absolute",
    },
    primaryTypo: {
        lineHeight: 27,
        left: "6.91%",
        color: Color.textPrimary,
        letterSpacing: 0,
        textAlign: "left",
        FontFamily: FontFamily.semiBold11,
        fontWeight: "500",
        position: "absolute",
    },
    titleTypo: {
        lineHeight: 19,
        fontSize: FontSize.size_sm_3,
        color: Color.textSecondary,
        letterSpacing: 0,
        textAlign: "left",
        FontFamily: FontFamily.semiBold11,
        fontWeight: "500",
    },
    deprecatedPosition: {
        bottom: "84.64%",
        top: "7.66%",
    },
    badgebaseSpaceBlock: {
        paddingVertical: 1,
        paddingHorizontal: 6,
        height: 17,
        borderRadius: 4,
        alignItems: "center",
        flexDirection: "row",
        overflow: "hidden",
    },
    badgeTypo: {
        fontSize: FontSize.size_xs_4,
        marginLeft: 3.8,
        lineHeight: 19,
        textAlign: "left",
        FontFamily: FontFamily.semiBold11,
        fontWeight: "500",
    },
    titlePosition: {
        left: "6.91%",
        position: "absolute",
    },
    deprecatedLayout: {
        width: "12.57%",
        height: "7.7%",
        flexDirection: "row",
        position: "absolute",
    },
    logoChild: {
        width: "33.59%",
        right: "66.41%",
        left: "0%",
        top: "0%",
        maxHeight: "100%",
        bottom: "0%",
        height: "100%",
    },
    metrix: {
        left: 63,
        fontSize: FontSize.subHeading3Bold_size,
        FontFamily: FontFamily.subHeading3Bold,
        color: Color.black60,
        textAlign: "center",
        fontWeight: "700",
        top: 8,
        position: "absolute",
    },
    logo: {
        height: "5.08%",
        width: "52.31%",
        top: "1.37%",
        right: "36.03%",
        bottom: "93.56%",
        left: "11.66%",
        display: "none",
        position: "absolute",
    },
    logoutChild: {
        width: 79,
        alignItems: "center",
        height: 24,
    },
    logout: {
        backgroundColor: Color.colorIndianred,
        paddingTop: Padding.p_2xs,
        paddingRight: Padding.p_2xs,
        paddingBottom: Padding.p_2xs,
        borderRadius: Border.br_base,
    },
    bottom: {
        top: 943,
        left: 16,
        flexDirection: "row",
        position: "absolute",
    },
    iconlybulklogout: {
        top: 848,
        left: 26,
        position: "absolute",
    },
    logout1: {
        height: "2.25%",
        width: "25.51%",
        top: "57.88%",
        left: "22.67%",
        fontSize: FontSize.bodyL18SpRegular_size,
        color: Color.destructive600,
        textAlign: "left",
    },
    figiftIcon: {
        overflow: "hidden",
    },
    freeGiftAwaits: {
        color: Color.black100,
        height: 19,
        marginLeft: 12,
        fontSize: FontSize.deprecatedBodyAlt_size,
    },
    figiftParent: {
        alignItems: "flex-end",
        flexDirection: "row",
    },
    upgradeYourAccount: {
        color: Color.black40,
        height: 18,
        display: "flex",
        fontSize: FontSize.semiBold11_size,
        alignItems: "center",
    },
    fichevronDownIcon: {
        overflow: "hidden",
    },
    upgradeYourAccountParent: {
        marginTop: 16,
        alignItems: "center",
        flexDirection: "row",
    },
    container: {
        top: 11,
        left: 20,
        position: "absolute",
    },
    banner: {
        top: 836,
        left: 32,
        backgroundColor: Color.colorBurlywood,
        width: 233,
        height: 82,
        borderRadius: Border.br_base,
        display: "none",
        position: "absolute",
        overflow: "hidden",
    },
    businessIcon: {
        top: 40,
        left: 26,
        position: "absolute",
    },
    testData: {
        lineHeight: 20,
        letterSpacing: 0,
        fontSize: FontSize.deprecatedBodyAlt_size,
        textAlign: "left",
    },
    track: {
        borderColor: Color.neutral100,
        borderStyle: "solid",
        position: "absolute",
        backgroundColor: Color.backgroundsContainer,
        borderWidth: 1,
        borderRadius: Border.br_3xs,
        right: "0%",
        left: "0%",
        bottom: "0%",
        top: "0%",
        height: "100%",
        width: "100%",
    },
    bobIcon: {
        height: "85.71%",
        width: "52.17%",
        top: "7.14%",
        right: "43.48%",
        bottom: "7.14%",
        left: "4.35%",
    },
    elementsLivemodeswitchoff: {
        width: 23,
        height: 14,
        marginLeft: 8,
    },
    testdata: {
        top: 793,
        left: 24,
        paddingLeft: Padding.p_3xs,
        paddingTop: Padding.p_3xs,
        paddingBottom: Padding.p_3xs,
        height: 39,
        alignItems: "center",
        flexDirection: "row",
        position: "absolute",
    },
    sidebar: {
        left: 0,
        width: 247,
        backgroundColor: Color.colorsWhite100,
        top: 0,
        position: "absolute",
        overflow: "hidden",
        height: 1465,
    },
    accountIcon: {
        display: "none",
    },
    accountName: {
        FontFamily: "PlusJakartaSans-SemiBold",
        color: Color.neutral500,
        marginLeft: 8,
        fontSize: FontSize.semiBold11_size,
        textAlign: "left",
    },
    iconchevrondown: {
        marginLeft: 8,
    },
    accountswitcher: {
        alignItems: "center",
        flexDirection: "row",
    },
    accountswitcherWrapper: {
        width: 165,
    },
    dashboardInner: {
        height: "1.09%",
        marginLeft: -671,
        top: "2.76%",
        bottom: "96.14%",
        width: 165,
        left: "50%",
        position: "absolute",
    },
    tabWrapper: {
        borderRadius: Border.br_xl,
        paddingVertical: Padding.p_11xs,
        paddingHorizontal: Padding.p_3xs,
        flexDirection: "row",
    },
    globaltab: {
        paddingHorizontal: 0,
        paddingVertical: Padding.p_5xs,
        height: 39,
        flexDirection: "row",
    },
    spacer40px: {
        width: 26,
        marginLeft: 14,
        height: 39,
    },
    right: {
        top: 763,
        right: 1329,
        justifyContent: "flex-end",
        alignItems: "center",
        flexDirection: "row",
        position: "absolute",
    },
    text: {
        fontSize: FontSize.size_smi_2,
        lineHeight: 17,
        color: Color.textIconsSecondary,
        FontFamily: FontFamily.deprecatedCaptionAlt,
        letterSpacing: 0,
        fontWeight: "500",
        textAlign: "center",
    },
    rightSectionIcon: {
        width: 10,
        height: 10,
        marginLeft: 7,
    },
    dateControlChild: {
        marginLeft: 7,
        height: 24,
        maxWidth: "100%",
        overflow: "hidden",
    },
    dateControl: {
        width: "101.75%",
        top: -1,
        right: "-0.82%",
        left: "-0.93%",
        borderColor: Color.colorDarkslategray_100,
        borderWidth: 0.9,
        height: 26,
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 3,
        borderStyle: "solid",
        alignItems: "center",
        flexDirection: "row",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",
    },
    dateControlWrapper: {
        width: "6.74%",
        top: 426,
        right: "74.86%",
        left: "18.4%",
        height: 24,
        position: "absolute",
    },
    dashboardChild: {
        right: "29.84%",
        left: "69.86%",
    },
    search1: {
        width: 456,
        color: Color.textSecondary,
        lineHeight: 16,
        marginLeft: 8,
        FontFamily: FontFamily.deprecatedCaptionAlt,
        fontSize: FontSize.semiBold11_size,
        textAlign: "left",

    },
    search: {

        paddingHorizontal: Padding.p_5xs,
        borderColor: Color.colorGainsboro_100,
        borderRadius: Border.br_xs,
        paddingVertical: Padding.p_9xs,
        outline: 'none',
        backgroundColor: "blue",
        position: "absolute",
        display: "none",
    },
    create: {
        color: Color.textBrand,
        FontFamily: FontFamily.deprecatedCaptionAlt,
        fontWeight: "500",
    },
    chevrondownIcon: {
        marginLeft: 4,
    },
    createButton: {
        borderRadius: Border.br_21xl,
        borderColor: Color.textBrand,
        paddingHorizontal: Padding.p_3xs,
    },
    help1: {
        color: Color.neutral600,
        marginLeft: 4,
        FontFamily: FontFamily.deprecatedCaptionAlt,
    },
    help: {
        justifyContent: "center",
        alignItems: "center",
    },
    notificationsIcon: {
        height: 16,
        width: 16,
        top: 0,
    },
    backgroundIcon: {
        top: 1,
        right: 0,
        position: "absolute",
    },
    text1: {
        right: 2.5,
        fontSize: FontSize.size_3xs,
        color: Color.colorsWhite100,
        width: 5,
        justifyContent: "center",
        alignItems: "center",
        fontWeight: "600",
        lineHeight: 16,
        FontFamily: FontFamily.SFMedium,
        display: "flex",
        textAlign: "center",
        top: 0,
    },
    badgeCount: {
        top: -4,
        right: -7,
        width: 11,
        height: 13,
    },
    settingsIcon: {
        marginLeft: 24,
    },
    rightGroup: {
        right: 40,
        flexDirection: "row",
        top: 4,
        justifyContent: "center",
        position: "absolute",
    },
    accountName1: {
        marginLeft: 8,
        color: Color.textPrimary,
        FontFamily: FontFamily.deprecatedCaptionAlt,
        fontWeight: "500",
    },
    accountswitcher1: {
        alignItems: "center",
        flexDirection: "row",
    },
    accountswitchercactuspractice: {
        flexDirection: "row",
        display: "none",
    },
    activateAccount: {
        FontFamily: FontFamily.textXsMedium,
        color: Color.attention600,
        fontWeight: "500",
    },
    arrowrightIcon: {
        marginLeft: 8,
        display: "none",
    },
    activateButton: {
        borderRadius: Border.br_18xl,
        backgroundColor: Color.attention100,
        paddingVertical: Padding.p_8xs,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: Padding.p_3xs,
        height: 24,
    },
    leftGroup: {
        top: 6,
        left: 40,
        flexDirection: "row",
        display: "none",
        position: "absolute",
    },
    toolbar: {
        height: "2.15%",
        width: "82.85%",
        bottom: "97.85%",

        shadowColor: "rgba(108, 140, 171, 0.15)",
        shadowRadius: 0,
        elevation: 0,
        shadowOpacity: 1,
        shadowOffset: {
            width: 0,
            height: 1,
        },
        backgroundColor: Color.backgroundsContainer,
        right: "0%",
        top: "0%",
        position: "absolute",
    },
    chartBottom: {
        top: 1449,
        right: 52,
        borderTopWidth: 0.9,
        height: 1,
        left: 264,
    },
    dashboardItem: {
        top: "90.03%",
        right: "56.37%",
        bottom: "9.66%",
        left: "43.33%",
        width: "0.3%",
        height: "0.31%",
        maxHeight: "100%",
        maxWidth: "100%",
        position: "absolute",
        overflow: "hidden",
    },
    ellipseIcon: {
        right: "3.38%",
        left: "96.32%",
    },
    bg: {
        height: "100.3%",
        width: "100.12%",
        top: "-0.15%",
        bottom: "-0.15%",
        left: "-0.06%",
        right: "-0.06%",
        borderColor: Color.colorGainsboro_200,
        borderWidth: 1,
        borderRadius: Border.br_3xs,
        backgroundColor: Color.colorsWhite100,
    },
    linesChild: {
        top: "99.69%",
        bottom: "-0.31%",
    },
    linesItem: {
        top: "74.69%",
        bottom: "24.69%",
    },
    linesInner: {
        top: "49.69%",
        bottom: "49.69%",
    },
    lineView: {
        top: "24.69%",
        bottom: "74.69%",
    },
    linesChild1: {
        top: "-0.31%",
        bottom: "99.69%",
    },
    lines: {
        height: "48.78%",
        top: "32.93%",
        bottom: "18.29%",
    },
    bgIcon: {
        height: "82.53%",
        bottom: "17.47%",
        right: "0%",
        left: "0%",
        top: "0%",
        maxHeight: "100%",
        width: "100%",
    },
    feb: {
        left: "0.13%",
        textAlign: "left",
    },
    mar: {
        left: "8.95%",
        textAlign: "center",
    },
    apr: {
        left: "17.78%",
        textAlign: "center",
    },
    may: {
        left: "26.33%",
        textAlign: "center",
    },
    jun: {
        left: "35.43%",
        textAlign: "center",
    },
    jul: {
        left: "43.58%",
        textAlign: "center",
    },
    aug: {
        left: "51.34%",
        textAlign: "center",
    },
    sep: {
        left: "60.29%",
        textAlign: "center",
    },
    oct: {
        left: "69.38%",
        textAlign: "center",
    },
    nov: {
        left: "78.34%",
        textAlign: "center",
    },
    dec: {
        left: "87.3%",
        textAlign: "center",
    },
    jan: {
        left: "96.38%",
        textAlign: "center",
    },
    graph: {
        height: "69.82%",
        top: "23.78%",
        bottom: "6.4%",
    },
    chartChild: {
        height: "22.26%",
        width: "0.12%",
        top: "59.3%",
        right: "62.55%",
        bottom: "18.45%",
        left: "37.33%",
        borderRightWidth: 1,
    },
    chartItem: {
        height: "3.05%",
        width: "1.26%",
        top: "56.4%",
        right: "61.98%",
        bottom: "40.55%",
        left: "36.76%",
    },
    text2: {
        top: "6.1%",
        fontSize: FontSize.bold16_size,
        lineHeight: 24,
        color: Color.gray900,
        left: "3.13%",
        position: "absolute",
        textAlign: "left",
    },
    unionChild: {
        height: "17.46%",
        width: "18.78%",
        top: "279.37%",
        right: "-219.88%",
        bottom: "-196.83%",
        left: "301.1%",
    },

    union: {
        width: 100,
        height: 63,
    },
    text3: {
        top: "41.27%",
        left: "32.33%",
        lineHeight: 22,
        color: Color.gray900,
        fontSize: FontSize.bold13_size,
        FontFamily: FontFamily.bold11,
        textAlign: "center",
        position: "absolute",
    },
    june2022: {
        top: "12.7%",
        left: "20.78%",
        color: Color.gray500,
        lineHeight: 20,
        fontSize: FontSize.semiBold11_size,
        textAlign: "center",
    },
    popup: {
        height: "19.21%",
        width: "12.04%",
        top: "34.45%",
        right: "56.59%",
        bottom: "46.34%",
        left: "31.37%",
        position: "absolute",
    },
    icon: {
        width: 18,
        height: 18,
        display: "none",
    },
    buttonName: {
        color: Color.gray500,
    },
    iconParent: {
        width: 126,
        flexDirection: "row",
    },
    buttonprimarywithIconLeft: {
        padding: Padding.p_base,
        borderRadius: Border.br_8xs,
        right: "76.34%",
        width: "23.66%",
        justifyContent: "center",
        alignItems: "center",
        left: "0%",
        bottom: "0%",
        top: "0%",
        height: "100%",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",
    },
    buttonName1: {
        color: Color.gray500,
    },
    buttonprimarywithIconLeft1: {
        right: "50.89%",
        left: "26.34%",
    },
    buttonprimarywithIconLeft2: {
        right: "25.45%",
        left: "51.79%",
    },
    buttonprimarywithIconLeft3: {
        left: "77.24%",
        right: "0%",
    },
    buttonprimarywithIconLeftParent: {
        height: "9.15%",
        width: "41.91%",
        top: "5.18%",
        right: "28.98%",
        bottom: "85.67%",
        left: "29.11%",
        position: "absolute",
    },
    text4: {
        width: "10.41%",
        top: "15.24%",
        fontSize: FontSize.size_15xl_9,
        letterSpacing: -1.3,
        left: "3.13%",
        position: "absolute",
    },
    glyphIcon: {
        height: "1.52%",
        width: "1.12%",
        top: "9.76%",
        right: "75.79%",
        bottom: "88.72%",
        left: "23.08%",
    },
    chart: {
        width: 827,
        left: 264,
    },
    bg2: {
        height: "100.24%",
        width: "100.31%",
        top: "-0.12%",
        right: "-0.17%",
        bottom: "-0.12%",
        borderRadius: 8,
        borderWidth: 0.8,
    },
    glyphIcon1: {
        height: "1.86%",
        width: "3.63%",
        top: "7.93%",
        right: "49.35%",
        bottom: "90.21%",
        left: "47.01%",
    },
    text5: {
        top: "5.12%",
        fontSize: FontSize.size_sm_4,
        color: Color.gray900,
        FontFamily: FontFamily.bold11,
        fontWeight: "700",
        lineHeight: 20,
        textAlign: "left",
    },
    icon4: {
        display: "none",
    },
    buttonName4: {
        color: Color.gray500,
    },
    iconParent1: {
        width: 84,
        flexDirection: "row",
    },
    buttonprimarywithIconLeft4: {
        //borderWidth: 0.7,
        padding: 11,
        //borderColor: Color.colorDarkgray,
        right: "76.34%",
        width: "23.66%",
        justifyContent: "center",
        borderRadius: 3,
        //borderStyle: "solid",
        alignItems: "center",
        left: "0%",
        bottom: "0%",
        top: "0%",
        height: "100%",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",
    },
    buttonName5: {
        color: Color.gray500,
    },
    buttonprimarywithIconLeft5: {
        right: "50.93%",
        left: "26.32%",
    },
    buttonprimarywithIconLeft6: {
        right: "25.46%",
        left: "51.78%",
    },
    buttonprimarywithIconLeft7: {
        left: "77.25%",
        right: "0%",
    },
    buttonprimarywithIconLeftGroup: {
        height: "6.07%",
        width: "75.24%",
        top: "26.37%",
        right: "17.63%",
        bottom: "67.56%",
    },
    bgIcon1: {
        width: "89.2%",
        right: "3.97%",
        left: "6.83%",
    },
    text6: {
        width: "23.64%",
        top: "11.49%",
        fontSize: FontSize.size_10xl_3,
        letterSpacing: -1.1,
        color: Color.valueColor,
        FontFamily: FontFamily.robotoMedium,
        textAlign: "left",
        fontWeight: "500",
    },
    chart2: {
        left: 1106,
        width: 294,
    },
    bg3: {
        height: "100.45%",
        width: "100.28%",
        top: "-0.23%",
        right: "-0.14%",
        bottom: "-0.23%",
        borderWidth: 1,
        borderRadius: Border.br_3xs,
        left: "-0.14%",
    },
    bgIcon2: {
        width: "89.17%",
        right: "3.98%",
        left: "6.85%",
    },
    text7: {
        fontSize: FontSize.size_lg_9,
    },
    documentsTransfered: {
        fontSize: FontSize.semiBold11_size,
    },
    primary: {
        top: "16.58%",
    },
    title: {
        top: "6.76%",
        left: "6.91%",
        position: "absolute",
    },
    leftwrapperIcon: {
        display: "none",
    },
    badgeLabel: {
        color: Color.success600,
        marginLeft: 3.8,
    },
    rightwrapperIcon: {
        marginLeft: 3.8,
        display: "none",
    },
    badgebase: {
        backgroundColor: Color.success100,
    },
    deprecatedBadge: {
        width: "13.09%",
        right: "48.81%",
        left: "38.09%",
        height: "7.7%",
        bottom: "84.64%",
        top: "7.66%",
        flexDirection: "row",
        position: "absolute",
    },
    chart21: {
        top: 468,
        width: 362,
        left: 264,
    },
    primary1: {
        height: "9.01%",
        width: "64.36%",
        top: "16.67%",
    },
    titleWrapper: {
        height: "15.77%",
        width: "26.8%",
        top: "3.6%",
        right: "66.3%",
        bottom: "80.63%",
        paddingTop: Padding.p_5xs,
        paddingRight: Padding.p_5xs,
        paddingBottom: Padding.p_5xs,
        flexDirection: "row",
    },
    badgeLabel1: {
        marginLeft: 3.8,
        color: Color.attention600,
    },
    badgebase1: {
        backgroundColor: Color.colorMistyrose,
    },
    deprecatedBadge1: {
        right: "53.73%",
        left: "33.7%",
        bottom: "84.64%",
        top: "7.66%",
    },
    chart3: {
        left: 651,
        top: 468,
        width: 362,
    },
    primary2: {
        top: "18.38%",
        fontSize: FontSize.size_lg_9,
    },
    title2: {
        top: "8.56%",
        left: "6.91%",
        position: "absolute",
    },
    deprecatedBadge2: {
        top: "9.46%",
        right: "62.54%",
        bottom: "82.84%",
        left: "24.89%",
    },
    chart4: {
        top: 463,
        left: 1038,
    },
    search2: {
        marginTop: -13,
        marginLeft: -229,
        paddingHorizontal: Padding.p_5xs,
        borderColor: Color.colorGainsboro_100,
        borderRadius: Border.br_xs,
        paddingVertical: Padding.p_9xs,
        top: "50%",
        left: "50%",
        backgroundColor: Color.colorsWhite100,
        position: "absolute",
    },
    searchWrapper: {
        left: 492,
        width: 456,
        top: 4,
        height: 24,
        position: "absolute",
    },
    dashboard: {
        backgroundColor: Color.colorGray_100,
        flex: 1,
        overflow: "hidden",
        height: 1465,
        width: "100%",
    },
    //selected button
    selectedButton: {
        borderColor: '#000', // Replace with the desired border color for the selected state
        borderWidth: 1, // Adjust the border width if needed

    },
    selectedText: {
        color: '#000', // Replace with the desired text color for the selected state
    },
    //selected button install
    selectedButtonInstall: {
        borderColor: '#000', // Replace with the desired border color for the selected state
        borderWidth: 1, // Adjust the border width if needed

    },
    selectedTextInstall: {
        color: '#000', // Replace with the desired text color for the selected state
    },

    
});